// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY2u-30aV6CjfPSvy1jsb_ZsqKbHCsQGY',
    appId: '1:203592669551:web:e048dc34b99184f879f09a',
    messagingSenderId: '203592669551',
    projectId: 'calories-app-e995f',
    authDomain: 'calories-app-e995f.firebaseapp.com',
    storageBucket: 'calories-app-e995f.firebasestorage.app',
    measurementId: 'G-690VV4LJNK',
    databaseURL: "https://calories-app-e995f-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7XF139qkw4Xt49nUUEAVS-MuO6wSI4d0',
    appId: '1:203592669551:android:fadb339791ce88f179f09a',
    messagingSenderId: '203592669551',
    projectId: 'calories-app-e995f',
    storageBucket: 'calories-app-e995f.firebasestorage.app',
    databaseURL: "https://calories-app-e995f-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTzoiVMWkWPCebR8jtIvHIfuy109TzILw',
    appId: '1:203592669551:ios:84cbca4c0eb735e179f09a',
    messagingSenderId: '203592669551',
    projectId: 'calories-app-e995f',
    storageBucket: 'calories-app-e995f.firebasestorage.app',
    iosBundleId: 'com.example.caloriesApp',
    databaseURL: "https://calories-app-e995f-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTzoiVMWkWPCebR8jtIvHIfuy109TzILw',
    appId: '1:203592669551:ios:84cbca4c0eb735e179f09a',
    messagingSenderId: '203592669551',
    projectId: 'calories-app-e995f',
    storageBucket: 'calories-app-e995f.firebasestorage.app',
    iosBundleId: 'com.example.caloriesApp',
    databaseURL: "https://calories-app-e995f-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY2u-30aV6CjfPSvy1jsb_ZsqKbHCsQGY',
    appId: '1:203592669551:web:c15d5e55852edd1a79f09a',
    messagingSenderId: '203592669551',
    projectId: 'calories-app-e995f',
    authDomain: 'calories-app-e995f.firebaseapp.com',
    storageBucket: 'calories-app-e995f.firebasestorage.app',
    measurementId: 'G-91ELV8L22Z',
    databaseURL: "https://calories-app-e995f-default-rtdb.firebaseio.com",
  );
}
